version: '3.8'

services:
  php-app:
    image: registry.digitalocean.com/adstat-digital-1/x-application:latest
    ports:
      - "3000:80"
    restart: always
    environment:
      - APP_ENV=production
